# idf common build

include($ENV{IDF_PATH}/tools/cmake/idf.cmake)
include(${PROJDIR}/scripts/idf_overrides.cmake)

message(NOTICE "IDF framework at: " $ENV{IDF_PATH})
message(NOTICE "IDF Version: ${IDF_VERSION_MAJOR}.${IDF_VERSION_MINOR}.${IDF_VERSION_PATCH}")

if(IDF_VERSION_MAJOR LESS 5 OR (IDF_VERSION_MAJOR EQUAL 5 AND IDF_VERSION_MINOR LESS 2))
    message(FATAL_ERROR "Build requires ESP-IDF v5.2+ or v6.x. Current version: ${IDF_VERSION_MAJOR}.${IDF_VERSION_MINOR}")
endif()

message(STATUS "External dependencies are being processed...")
set(Dependencies_Platform_ESP ON)
include(${PROJDIR}/scripts/dependencies.cmake)

set(PLATFORM_MODULES
        freertos
        esptool_py
        esp-mqtt-src
        log
        esp_event
        esp_wifi
        esp_eth
        mdns
        esp_http_server
        esp_http_client
        esp_driver_gpio
        esp_driver_rmt
        esp_ringbuf
        hal
        esp_netif
        esp_https_ota
        app_update
        nvs_flash
        esp_timer
        Kconfig
)
set(SDKCONFIG_DEFAULTS_LIST "")
list(APPEND SDKCONFIG_DEFAULTS_LIST "${PROJDIR}/support/sdkconfig.default")

option(ENABLE_ADVANCED_APP_CTRL "Enable DALI-2 App Controller" OFF)
option(ENABLE_ETHERNET "Compile for Ethernet instead of Wi-Fi" OFF)
option(DISABLE_WEBUI "Opt-out WebUI" OFF)

set(_OVERRIDES_FILE "${CMAKE_BINARY_DIR}/ci_overrides.default")
file(WRITE ${_OVERRIDES_FILE} "# Auto-generated by CMake from -D flags\n")

if(ENABLE_ADVANCED_APP_CTRL)
    file(APPEND ${_OVERRIDES_FILE} "CONFIG_DALI2MQTT_ADVANCED_APP_CTRL=y\n")
endif()

if(ENABLE_ETHERNET)
    file(APPEND ${_OVERRIDES_FILE} "CONFIG_DALI2MQTT_NET_WIFI=n\n")
    file(APPEND ${_OVERRIDES_FILE} "CONFIG_DALI2MQTT_NET_ETHERNET=y\n")
endif()

if(DISABLE_WEBUI)
    file(APPEND ${_OVERRIDES_FILE} "CONFIG_DALI2MQTT_ENABLE_WEBUI=n\n")
endif()

string(TOLOWER "${CMAKE_BUILD_TYPE}" _BUILD_TYPE_LOWER)
if(EXISTS "${PROJDIR}/support/sdkconfig.${_BUILD_TYPE_LOWER}.default")
    list(APPEND SDKCONFIG_DEFAULTS_LIST "${PROJDIR}/support/sdkconfig.${_BUILD_TYPE_LOWER}.default")
endif()

if(EXISTS "${ESP_BUILD_UTILS_PATH}/sdkconfig.default")
    list(APPEND SDKCONFIG_DEFAULTS_LIST "${ESP_BUILD_UTILS_PATH}/sdkconfig.default")
endif()

if(EXISTS "${ESP_BUILD_UTILS_PATH}/${CMAKE_BUILD_TYPE}/sdkconfig.default")
    list(APPEND SDKCONFIG_DEFAULTS_LIST "${ESP_BUILD_UTILS_PATH}/${CMAKE_BUILD_TYPE}/sdkconfig.default")
endif()
list(APPEND SDKCONFIG_DEFAULTS_LIST "${_OVERRIDES_FILE}")

if(EXISTS "${PROJDIR}/support/sdkconfig.user.default")
    list(APPEND SDKCONFIG_DEFAULTS_LIST "${PROJDIR}/support/sdkconfig.user.default")
endif()

if(EXISTS "${ESP_BUILD_UTILS_PATH}/sdkconfig.user.default")
    list(APPEND SDKCONFIG_DEFAULTS_LIST "${ESP_BUILD_UTILS_PATH}/sdkconfig.user.default")
endif()

set(CURRENT_SDKCONFIG "${ESP_BUILD_UTILS_PATH}/${CMAKE_BUILD_TYPE}/sdkconfig")

if(BUILD_UNITY)
    set(CURRENT_SDKCONFIG "${CMAKE_BINARY_DIR}/sdkconfig")
    if(EXISTS "${PROJDIR}/tests/sdkconfig.default")
        list(APPEND SDKCONFIG_DEFAULTS_LIST "${PROJDIR}/tests/sdkconfig.default")
    endif()
    message("-------- TEST BACKEND BUILD -------")
    list(APPEND PLATFORM_MODULES unity)
endif()

message("Build for: " ${CMAKE_BUILD_TYPE})
message(STATUS "Uses Sdkconfig: ${CURRENT_SDKCONFIG}")

idf_build_component(${ESP_BUILD_UTILS_PATH}/../../Kconfig)
idf_build_component(${ESP_PROTO_BASEDIR}/mdns)
idf_build_component(${esp-mqtt_SOURCE_DIR})

idf_build_process(${TARGET}
        COMPONENTS
        ${PLATFORM_MODULES}
        SDKCONFIG
        ${CURRENT_SDKCONFIG}
        PROJECT_VER ${CMAKE_PROJECT_VERSION}
        PROJECT_DIR ${PROJDIR}
        SDKCONFIG_DEFAULTS "${SDKCONFIG_DEFAULTS_LIST}"
        BUILD_DIR ${CMAKE_BINARY_DIR}
)