if(NOT WIN32 OR DEFINED ENV{WT_SESSION} OR DEFINED ENV{TERM})
    string(ASCII 27 Esc)
    set(_CLR_RESET  "${Esc}[0m")
    set(_CLR_BOLD   "${Esc}[1m")
    set(_CLR_CYAN   "${Esc}[1;36m")
    set(_CLR_GREEN  "${Esc}[1;32m")
    set(_CLR_YELLOW "${Esc}[1;33m")
    set(_CLR_GRAY   "${Esc}[90m")
else()
    set(_CLR_RESET  "")
    set(_CLR_BOLD   "")
    set(_CLR_CYAN   "")
    set(_CLR_GREEN  "")
    set(_CLR_YELLOW "")
    set(_CLR_GRAY   "")
endif()

if(CONFIG_DALI2MQTT_NET_ETHERNET)
    if(CONFIG_DALI2MQTT_ETH_TYPE_SPI_W5500)
        set(_SUMMARY_NET "Ethernet W5500 (SPI${CONFIG_DALI2MQTT_ETH_SPI_HOST}: SCK=${CONFIG_DALI2MQTT_ETH_SPI_SCK_PIN}, MOSI=${CONFIG_DALI2MQTT_ETH_SPI_MOSI_PIN}, MISO=${CONFIG_DALI2MQTT_ETH_SPI_MISO_PIN}, CS=${CONFIG_DALI2MQTT_ETH_SPI_CS_PIN}, INT=${CONFIG_DALI2MQTT_ETH_SPI_INT_PIN})")
    else()
        set(_SUMMARY_NET "Ethernet Internal RMII (LAN8720)")
    endif()
else()
    set(_SUMMARY_NET "Wi-Fi")
endif()

if(CONFIG_DALI2MQTT_PRECONFIGURED)
    string(REPLACE "\"" "" _CLEAN_URI "${CONFIG_DALI2MQTT_MQTT_BROKER_URI}")
    if("${_CLEAN_URI}" STREQUAL "")
        set(_SUMMARY_DEPLOY "${_CLR_YELLOW}Pre-configured (Incomplete: URI is empty!)${_CLR_RESET}")
    else()
        set(_SUMMARY_DEPLOY "${_CLR_CYAN}Pre-configured${_CLR_RESET} (${_CLEAN_URI})")
    endif()
else()
    set(_SUMMARY_DEPLOY "${_CLR_GREEN}Interactive${_CLR_RESET}")
endif()

#[[
if(CONFIG_DALI2MQTT_ENABLE_WEBUI)
]]
    set(_SUMMARY_WEBUI "${_CLR_GREEN}Enabled${_CLR_RESET}")
#[[else()
    set(_SUMMARY_WEBUI "${_CLR_YELLOW}Disabled${_CLR_RESET}")
endif()]]

if(CONFIG_DALI2MQTT_MQTT_HOMEASSISTANT_DISCOVERY_ENABLED)
    set(_SUMMARY_HASS "${_CLR_GREEN}Enabled${_CLR_RESET} (by default)")
else()
    set(_SUMMARY_HASS "${_CLR_GRAY}Disabled (by default)${_CLR_RESET}")
endif()

string(REPLACE "\"" "" _CLEAN_TOPIC "${CONFIG_DALI2MQTT_MQTT_BASE_TOPIC}")

message("")
message("${_CLR_CYAN}======================================================================${_CLR_RESET}")
message("${_CLR_BOLD}   DALI-to-MQTT Bridge v${PROJVER} (${TARGET} / ${CMAKE_BUILD_TYPE})${_CLR_RESET}")
message("${_CLR_CYAN}======================================================================${_CLR_RESET}")
message("  ${_CLR_BOLD}Target Chip      :${_CLR_RESET} ${TARGET} (${CMAKE_BUILD_TYPE})")
message("  ${_CLR_BOLD}DALI Bus 0       :${_CLR_RESET} RX GPIO ${CONFIG_DALI2MQTT_DALI_RX_PIN}, TX GPIO ${CONFIG_DALI2MQTT_DALI_TX_PIN}")
message("  ${_CLR_BOLD}Network Interface:${_CLR_RESET} ${_SUMMARY_NET}")
message("  ${_CLR_BOLD}Deployment Mode  :${_CLR_RESET} ${_SUMMARY_DEPLOY}")
message("  ${_CLR_BOLD}MQTT Base Topic  :${_CLR_RESET} ${_CLEAN_TOPIC}")
message("  ${_CLR_BOLD}HA Auto-Discovery:${_CLR_RESET} ${_SUMMARY_HASS}")
message("  ${_CLR_BOLD}Web UI Server    :${_CLR_RESET} ${_SUMMARY_WEBUI}")
message("${_CLR_CYAN}======================================================================${_CLR_RESET}")
message("")
